
library(data.table)
library(geodist)
library(ggforce)
library(ggplot2)
library(ggrepel)
library(ggthemes)
library(grid)
library(gridExtra)
library(janitor)
library(Metrics)
library(patchwork)
library(readxl)
library(rgeos)
library(rnaturalearth)
library(rnaturalearthdata)
library(rprojroot)
library(scales)
library(sf)
library(stringr)
library(targets)



# library(caret)

# library(grid)
# #library(gridExtra)
# #library(gt)
# library(multcompView)
# library(olsrr)
# library(parzer)
# library(quantreg)
# 
# library(terra)
# library(visNetwork)
